# Generated by Django 6.0.2 on 2026-02-20 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='products',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='products',
            name='in_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_available',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='main',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_specification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
